# Generated by Django 6.1 on 2026-08-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='歌手')),
                ('album', models.CharField(blank=True, max_length=200, verbose_name='专辑')),
                ('genre', models.CharField(blank=True, choices=[('pop', '流行'), ('rock', '摇滚'), ('electronic', '电子'), ('hiphop', '说唱'), ('rnb', 'R&B'), ('instrumental', '纯音乐'), ('classical', '古典'), ('jazz', '爵士'), ('folk', '民谣'), ('acoustic', '原声'), ('lofi', 'Lo-Fi'), ('ambient', '氛围')], max_length=50, verbose_name='曲风')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔，如：relaxing,calm,instrumental', max_length=300, verbose_name='情绪标签')),
                ('duration', models.FloatField(default=0, verbose_name='时长(秒)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='本地文件路径')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面')),
                ('source', models.CharField(choices=[('local', '本地'), ('online', '在线')], default='local', max_length=20, verbose_name='来源')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='源内ID')),
                ('source_url', models.CharField(blank=True, max_length=1000, verbose_name='播放地址')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['genre'], name='music_song_genre_803ef6_idx'), models.Index(fields=['source'], name='music_song_source_228e2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True, verbose_name='播放时间')),
                ('duration_sec', models.FloatField(default=0, verbose_name='听歌时长(秒)')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_records', to='music.song')),
            ],
            options={
                'verbose_name': '听歌记录',
                'verbose_name_plural': '听歌记录',
                'ordering': ['-listened_at'],
            },
        ),
    ]
