# Generated by Django 6.1 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_fetched',
            field=models.BooleanField(default=False, help_text='无本地歌词时是否已尝试在线获取', verbose_name='已尝试获取歌词'),
        ),
    ]
