# Generated by Django 6.1 on 2026-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_lyrics_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cloud_url',
            field=models.CharField(blank=True, help_text='本地歌曲上传对象存储后的公网直链', max_length=1000, verbose_name='云端直链'),
        ),
    ]
