"""
Django settings for cloud_music project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 将 apps 目录加入模块搜索路径，app 一律放在 apps/ 下
sys.path.insert(0, str(BASE_DIR / "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 仓库公开后不在代码中写死真实密钥：优先读取环境变量 DJANGO_SECRET_KEY，
# 未设置时使用下方占位值（仅供本地开发；部署到公网前务必设置自己的密钥）。
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-REPLACE_ME_set_DJANGO_SECRET_KEY_env_var",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许任意 Host 访问（配合访问口令保护，供内网穿透/局域网分享使用）
ALLOWED_HOSTS = ["*"]

# 花生壳/内网穿透 HTTPS 映射：花生壳服务端终结 TLS 后以 HTTP 转发到本机，
# 依赖请求头 X-Forwarded-Proto: https 让 Django 识别原始请求为 HTTPS，
# 保证 Cookie、重定向、绝对 URL 等行为在 HTTPS 下正确。
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 允许花生壳免费域名通过 CSRF Origin 校验，避免 https://xxx.vicp.fun 这类域名提交口令/表单时报 403
CSRF_TRUSTED_ORIGINS = [
    "https://129ge21m16254.vicp.fun",
    "https://*.vicp.fun",
    "https://*.gicp.net",
    "https://*.oray.fun",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ---- 云律板块 ----
    'music',       # 板块1 音乐核心：模型、曲库、播放 API
    'playlists',   # 板块3 歌单管理
    'lyrics',      # 板块4 歌词同步
    'recommend',   # 板块5 推荐系统
    'mood',        # 板块6 AI 情绪点歌台
    'posters',     # 板块7 歌词海报
    'report',      # 板块8 听歌报告与点歌排行榜
    'web',         # 板块2 播放器前端（页面渲染）
    'gate',        # 访问控制：分享给朋友时用的口令验证
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gate.middleware.AccessCodeMiddleware',  # 访问口令保护
]

ROOT_URLCONF = 'cloud_music.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cloud_music.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# 用户上传文件（歌单封面等）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 静态资源云化（方案二：JS/CSS/封面图全部走对象存储，远程首屏不再过隧道）
# - 开启：把 tools/cloud_config.json 中 static_cdn.enabled 置为 true
#   （static_cdn.base 留空则自动使用对象存储的 public_domain）
# - 回滚：把 enabled 置为 false，或设置环境变量 CLOUD_STATIC_BASE=off，
#   页面立即回到本地加载静态资源，无需改代码
# - 配套上传命令：python manage.py upload_statics
def _load_static_cdn_base():
    try:
        import json
        cfg_path = BASE_DIR / "tools" / "cloud_config.json"
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
        sc = cfg.get("static_cdn") or {}
        if not sc.get("enabled"):
            return ""
        base = (sc.get("base") or "").strip().rstrip("/")
        if base:
            return base
        provider = (cfg.get("provider") or "").strip().lower()
        return (cfg.get(provider) or {}).get("public_domain", "").strip().rstrip("/")
    except Exception:
        return ""

_env_cdn = os.environ.get("CLOUD_STATIC_BASE")
if _env_cdn is None:
    CLOUD_STATIC_BASE = _load_static_cdn_base()
elif _env_cdn.strip().lower() in ("", "off", "0"):
    CLOUD_STATIC_BASE = ""
else:
    CLOUD_STATIC_BASE = _env_cdn.strip().rstrip("/")

# 本地音乐库根目录
MUSIC_LIBRARY_DIR = BASE_DIR / 'music_library'

# 分享访问口令：发给朋友时用的验证口令（为空表示不启用口令保护）
# 修改这里即可更换口令
ACCESS_CODE = os.environ.get('YUNLV_ACCESS_CODE', 'yunlv888')

# Jamendo 开放平台 client_id（在 https://developer.jamendo.com/ 注册应用后获取）
# 可用环境变量 YUNLV_JAMENDO_ID 覆盖，方便分享时隐藏
JAMENDO_CLIENT_ID = os.environ.get('YUNLV_JAMENDO_ID', '711e2909')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
