# Generated by Django 6.1 on 2026-08-28 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歌单名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='playlist_covers/', verbose_name='封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='排序位置')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='playlists.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music.song')),
            ],
            options={
                'verbose_name': '歌单歌曲',
                'verbose_name_plural': '歌单歌曲',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('playlist', 'song'), name='uniq_playlist_song')],
            },
        ),
    ]
